### ISSUE TITLE
Unable to run Tsung on remote hosts

### ISSUE THREAD

**Issue by Nesh108** [processone/tsung#177] opened 2016-05-06 20:41 UTC
Hello,
I have been trying to play around with Tsung for a couple of days now and I thought I would ask directly here for clarifications since I coudn't get it to work in any way.

First of all, here is what I did:
- I setup ssh keys in such a way that it is possible to connect to the clients without password.
- I also setup ssh keys for the other way around (from client to controller)
- Tried to run a couple of tests using `vm_controller`, that seemed to work.

Here is my current config file:

``` XML
<?xml version="1.0"?>
   <!DOCTYPE tsung SYSTEM "/opt/local/share/tsung/tsung-1.0.dtd">
   <tsung loglevel="warning">
   <clients>
      <client host="tsung1" cpu="2" maxusers="300"/>
      <client host="tsung2" cpu="2" maxusers="300"/>
      <client host="tsung3" cpu="2" maxusers="300"/>
      <client host="tsung4" cpu="2" maxusers="300"/>
   </clients>
   <servers>
      <server host="192.168.1.128" port="4000" type="tcp"/>
   </servers>
   <load>
      <arrivalphase phase="1" duration="30" unit="second">
         <users arrivalrate="100" unit="second"/>
      </arrivalphase>
    </load>
   <sessions>
      <session probability="20" name="es_load1" type="ts_http">
         <request>
            <http url="/name/Rome" method="GET"/>
         </request>
      </session>
      <session probability="20" name="es_load2" type="ts_http">
         <request>
            <http url="/name/Paris" method="GET"/>
         </request>
      </session>
      <session probability="20" name="es_load3" type="ts_http">
         <request>
            <http url="/name/London" method="GET"/>
         </request>
      </session>
      <session probability="20" name="es_load4" type="ts_http">
         <request>
            <http url="/name/Helsinki" method="GET"/>
         </request>
      </session>
      <session probability="20" name="es_load5" type="ts_http">
         <request>
            <http url="/name/Tokyo" method="GET"/>
         </request>
      </session>
   </sessions>
 </tsung>
```

I run the test with `tsung -f stress_test.xml start`.

Since I was getting `Can't start newbeam on host 'XXXXX (reason: timeout) ! Aborting!`, I tried several ways to fix it:
- Double checked everything suggested in the [documentation FAQ](http://tsung.erlang-projects.org/user_manual/faq.html)
- Tested every single node once more
- Re-compiled tsung from source (this time from this repo)
- Used the following script:

``` sh
#!/bin/sh
/usr/bin/ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $@
```

And running the script as `tsung -f stress_test.xml -r ssh_no_check start`.

Still no luck.

What can I do? For more info: I am running the 4 nodes on 4 separate VMs with Ubuntu. They are running on another computer in my LAN and they seem to be working fine.

I am really lost but I would really like to use this seemingly fantastic tool!

Thanks in advance!

/Nesh

**Comment by subbu05** [comment] 2016-07-09 20:03
Few things
1. Ensure you are able to SSH between nodes without password of ssh key. If not configure ssh-keyless settings correctly.
2.Create a file ~/.ssh/config with following content
Host *
    StrictHostKeyChecking no
3.chmod 400 ~/.ssh/config
4.Ensure the client hosts are accessible using hostname instead IP. (try ping or ssh on client hostnames)
Try running the tests now.

If still doesn't work reply I will help you.

**Comment by harekumar** [comment] 2016-09-27 07:41
Hi @Nesh108 Did you got it running? I'm also struggling to setup the distributed cluster and kinda stuck in the same situation. Please suggest the solution if you have got it running successfully.

**Comment by tisba** [comment] 2016-09-27 07:44
Did you also make sure that all generator nodes can connect back to the controller? This is something that is often overlooked. Did you check your auth.log? Are you seeing login attempts/errors on all nodes?

**Comment by harekumar** [comment] 2016-09-27 10:34
Hi @tisba Yes in secure.log file, I can see the success logs for session opening & termination at remote hosts. But I'm getting [this error](http://pastebin.com/7sB6BZtv) in erl_dump on my remote machine after running tsung start command. 

For the setup I'm just using my local machine as controller & one remote tsung client.  Version of the tsung & erlang installed on both the machines are the same. 

Kindly suggest, what is the cause of the error in erl_dump & what could be the possible fix?

**Comment by Nesh108** [comment] 2016-09-27 11:02
@harekumar nah. I gave up. JMeter is such a better and more reliable alternative. Also it comes with plugins which can generate really good graphs, so that sealed the deal for me.

**Comment by einsteinarbert** [comment] 2016-10-21 03:12
Hey, every body, I have just tried it with same virtual machine + same tsung(1.5.1) + same erlang(V7.3) + same username for all clusters, also insert real server to benchmark into /etc/hosts file, OS is ubuntu 16.04 lts, and it worked. Anyone let's setting like that, please post your results.
I guest that my ssh was worked, but Erlang short name or some thing wrong when try to slave:start() function. So let test it with same username on all clusters.

**Comment by subbu05** [comment] 2016-12-21 21:53
Ensure ssh key verification is disabled
~/.ssh/config Host * StrictHostKeyChecking no UserKnownHostsFile=/dev/null

Make sure all ports are accessible across controller and worker nodes. If it is in the cloud make sure firewall or security groups allow all ports.
3.Erlang, Tsung must have same version.

4.Ensure all machines are reachable to each other

5.Run erlang test

erl -rsh ssh -name subbu -setcookie tsung Erlang R16B03-1 (erts-5.10.4) [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V5.10.4 (abort with ^G) (daya@ip-10-0-100-224.ec2.internal)1> slave:start("worker1.com",bar,"-setcookie tsung").

Warning: Permanently added 'worker1,10.0.100.225' (ECDSA) to the list of known hosts. {ok,bar@worker1}

Run this test from controller to all worker nodes.

You should be able run tests without any issues.

Good Luck!

Subbu

**Comment by kanawaden** [comment] 2017-10-10 09:18
Hello,

Anybody manage to solve this issue?

I'm also facing similar issue. Also, I have tried all the steps suggested by @subbu05. Below is my error:
ts_config_server:(0:<0.77.0>) Can't start newbeam on host slave2 (reason: timeout) ! Aborting!

FYI, my erlang version is 5.8.5 & tsung version is 1.5.1 - I hope this is not the issue.

Thanks,
Nilesh

**Comment by einsteinarbert** [comment] 2017-10-10 09:30
@kanawaden Do you try to config that: same user for all clusters

**Comment by kanawaden** [comment] 2017-10-10 16:49
Yes, all my machines configured with same user. BTW, all my machines are in AWS.

**Comment by einsteinarbert** [comment] 2017-10-11 04:43
did you ping through each others node erlang ok? from cmd of erlang

**Comment by kanawaden** [comment] 2017-10-11 05:38
I can do "ssh <hostname> erl" successfully but below command fails with timeout error.
"erl -rsh ssh -sname foo -setcookie mycookie" 

Among all precautions mentioned [here](http://tsung.erlang-projects.org/user_manual/faq.html), I suspect the issue is with firewall. Although I opened All TCP ports for Inbound traffics it somehow not working.

**Comment by kanawaden** [comment] 2017-10-11 06:43
I just double check, no firewall issue. Currently, opened all ports for all IP from everywhere. Also, I have checked all the troubleshooting steps which is taken care of, still error is not resolved.

Any pointers?? (Note: I'm using 3 aws instances of m4.large type)

**Comment by einsteinarbert** [comment] 2017-10-11 06:59
Could you using [erl +v] and show me what it do when run, also create a new
customize ssh script and show your log:

#!/bin/sh

echo "$0" "$@" > /tmp/my-ssh.log
ssh -v "$@"  2>&1 | tee -a /tmp/my-ssh.log

>

**Comment by kanawaden** [comment] 2017-10-11 07:22
Here is the output in /tmp/my-ssh.log file:

test.sh
usage: ssh [-1246AaCfGgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
           [-D [bind_address:]port] [-E log_file] [-e escape_char]
           [-F configfile] [-I pkcs11] [-i identity_file]
           [-J [user@]host[:port]] [-L address] [-l login_name] [-m mac_spec]
           [-O ctl_cmd] [-o option] [-p port] [-Q query_option] [-R address]
           [-S ctl_path] [-W host:port] [-w local_tun[:remote_tun]]
           [user@]hostname [command]

**Comment by einsteinarbert** [comment] 2017-10-11 07:27
easy to see your ssh was wrong syntax, recheck your ssh statement

On Oct 11, 2017 14:22, "kanawaden" <notifications@github.com> wrote:

Here is the output in /tmp/my-ssh.log file:

test.sh
usage: ssh [-1246AaCfGgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
[-D [bind_address:]port] [-E log_file] [-e escape_char]
[-F configfile] [-I pkcs11] [-i identity_file]
[-J [user@]host[:port]] [-L address] [-l login_name] [-m mac_spec]
[-O ctl_cmd] [-o option] [-p port] [-Q query_option] [-R address]
[-S ctl_path] [-W host:port] [-w local_tun[:remote_tun]]
[user@]hostname [command]

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/processone/tsung/issues/177#issuecomment-335708974>,
or mute
the thread

**Comment by kanawaden** [comment] 2017-10-11 07:37
Please check now --

test.sh slave1
OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017^M
debug1: Reading configuration data /home/ec2-user/.ssh/config^M
debug1: /home/ec2-user/.ssh/config line 1: Applying options for slave1^M
debug1: Reading configuration data /etc/ssh/ssh_config^M
debug1: /etc/ssh/ssh_config line 58: Applying options for *^M
debug1: Connecting to 10.xxx.xxx.xxx [10.xxx.xxx.xxx] port 22.^M
debug1: Connection established.^M
debug1: key_load_public: No such file or directory^M
debug1: identity file /home/ec2-user/.ssh/non-prod-apps.pem type -1^M
debug1: key_load_public: No such file or directory^M
debug1: identity file /home/ec2-user/.ssh/non-prod-apps.pem-cert type -1^M
debug1: Enabling compatibility mode for protocol 2.0^M
debug1: Local version string SSH-2.0-OpenSSH_7.4^M
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1^M
debug1: match: OpenSSH_6.6.1 pat OpenSSH_6.6.1* compat 0x04000000^M
debug1: Authenticating to 10.xxx.xxx.xxx:22 as 'ec2-user'^M
debug1: SSH2_MSG_KEXINIT sent^M
debug1: SSH2_MSG_KEXINIT received^M
debug1: kex: algorithm: curve25519-sha256@libssh.org^M
debug1: kex: host key algorithm: ecdsa-sha2-nistp256^M
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none^M
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none^M
debug1: kex: curve25519-sha256@libssh.org need=64 dh_need=64^M
debug1: kex: curve25519-sha256@libssh.org need=64 dh_need=64^M
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY^M
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:GeFgcmduVwo9eS7lPrtepJqbGi1B7cL524yB+3DBbQo^M
Warning: Permanently added '10.xxx.xxx.xxx' (ECDSA) to the list of known hosts.^M
debug1: rekey after 134217728 blocks^M
debug1: SSH2_MSG_NEWKEYS sent^M
debug1: expecting SSH2_MSG_NEWKEYS^M
debug1: SSH2_MSG_NEWKEYS received^M
debug1: rekey after 134217728 blocks^M
debug1: SSH2_MSG_SERVICE_ACCEPT received^M
debug1: Authentications that can continue: publickey^M
debug1: Next authentication method: publickey^M
debug1: Trying private key: /home/ec2-user/.ssh/non-xxxxx.pem^M
debug1: Authentication succeeded (publickey).^M
Authenticated to 10.xxx.xxx.xxx ([10.xxx.xxx.xxx]:22).^M
debug1: channel 0: new [client-session]^M
debug1: Requesting no-more-sessions@openssh.com^M
debug1: Entering interactive session.^M
debug1: pledge: network^M
debug1: Sending environment.^M
debug1: Sending env LANG = en_US.UTF-8^M
Last login: Wed Oct 11 07:21:13 2017 from master^M^M
^M
       __|  __|_  )^M
       _|  (     /   Amazon Linux AMI^M
      ___|\___|___|^M
^M
https://aws.amazon.com/amazon-linux-ami/2017.03-release-notes/^M
14 package(s) needed for security, out of 29 available^M
Run "sudo yum update" to apply all updates.^M
Amazon Linux version 2017.09 is available.^M

**Comment by einsteinarbert** [comment] 2017-10-11 08:26
see ssh is ok, now run erl command with verbose flag and show log for what
happened.

**Comment by kanawaden** [comment] 2017-10-11 08:48
[ec2-user@ip-10-xxx-xxx-xxx ~]$ ssh slave1 erl +v
Warning: Permanently added '10.xxx.xxx.xxx' (ECDSA) to the list of known hosts.
warning: -v (only in debug compiled code)
Eshell V5.8.5  (abort with ^G)
1> put(a,100).
undefined
2> get().
[{a,100}]
3>

**Comment by einsteinarbert** [comment] 2017-10-11 09:38
Try to ping to other nodes:
*net_adm:ping().*
What result is?

**Comment by einsteinarbert** [comment] 2017-10-11 09:42
Did you try to use other version of Erlang: v6.2 or v7, v8.
Try this:
Ensure ssh key verification is disabled ~/.ssh/config Host *
StrictHostKeyChecking no UserKnownHostsFile=/dev/null
(And I has been using Ubuntu 16 when successfully run test of TSUNG)

2017-10-11 16:38 GMT+07:00 Hieu than hieu <hieu19926@gmail.com>:

> Try to ping to other nodes:
> *net_adm:ping().*
> What result is?
>

**Comment by kanawaden** [comment] 2017-10-11 09:43
(foo@ip-10-xxx-xxx-xxx)3> net_adm:ping(foo@slave1).
pang

**Comment by einsteinarbert** [comment] 2017-10-11 09:58
When start erlang, add flag: -sname your_node
And rec check ping node, your result above show that your nodes connection
is not ok.

**Comment by kanawaden** [comment] 2017-10-12 02:22
Yes, you are right. It fails! Any idea what is wrong and how to fix it?

**Comment by einsteinarbert** [comment] 2017-10-12 02:59
Dear Waden,
did you forget -sname (short name).
You must to config erlang until you ping between nodes,the start cmd of
erlang must has config with -sname like:
*erl -sname foo@elimayost -setcookie secret*
https://stackoverflow.com/questions/22202204/how-do-i-connect-to-an-erlang-node-which-uses-a-short-name
https://stackoverflow.com/questions/13753741/cant-get-two-erlang-nodes-to-communicate
After ping ok, then config tsung, look at ip addr must inside <ip> tag:
https://gist.github.com/huberflores/2827905

**Comment by kanawaden** [comment] 2017-10-12 05:24
I'm unable to connect erl nodes to one another. net_kernel:connect_node(slave1) command always return false. Which protocol erlang uses to form connection between nodes?

**Comment by einsteinarbert** [comment] 2017-10-12 06:43
Read link I posted above, first - try in local host, ok then try in Lan
network (same network mask) then try in other network with config in hosts

**Comment by piisalie** [comment] 2018-04-26 20:43
I also had trouble connecting a Tsung controller to Tsung worker nodes in AWS.

The resolution ended up being:

On the Controller node:
* The `/etc/hosts` or equivalent file on the controller should have entries for the nodes like `<node1ip> ts1` etc.
* Set the controller's host name to something like `controller` (not necessary but I found it easier to automate)
* Should have passwordless ssh access to all nodes
* Should have port access to the nodes for the EPMD

On the worker node: 
* The `/etc/hosts` or equivalent file on the worker nodes should also have an entry like `<controllerip> controller` (or whatever the controller's hostname is)
* Set the node's host name to match whatever is in the controller's hosts file (like `ts1`)

In this way starting Tsung on the controller and using the `ts1` `ts2` etc in the `<clients>` field just worked(tm).

**Comment by tisba** [comment] 2018-08-22 11:52
Closing this issue for now. The problem from the original poster is no longer an issue.

**Closed by tisba** 2018-08-22 11:52 UTC
