### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by okeuday** [processone/tsung#238] opened 2017-05-26 18:42 UTC
The last official release of Tsung is 1.6.0 from 2015-07-20 and there have been many changes to both Tsung and Erlang since that time.  Could you please make a new release at a point where this repository is stable, even if it is only a new tag following this version number scheme?

**Comment by nniclausse** [comment] 2017-05-31 07:13
The master branch is considered stable, but i agree, we definitely need to publish releases more often. I'll try to do that ASAP.

**Comment by okeuday** [comment] 2017-07-08 01:07
@nniclausse Normal operation of tsung generates a crash dump which causes the tsung.log to be overwritten with the console output

    {"Kernel pid terminated",application_controller,"{application_terminated,tsung_controller,shutdown}"}
    Kernel pid terminated (application_controller) ({application_terminated,tsung_controller,shutdown})
    
    Crash dump is being written to: erl_crash.dump...done

When running the latest commit on x86 with an install based on https://github.com/CloudI/loadtests/tree/master/live_cd/alpine#readme , so the master branch doesn't appear to be ready for use yet.

**Comment by nniclausse** [comment] 2017-07-10 08:52
Can you provide the XML config file ?

**Comment by okeuday** [comment] 2017-07-10 16:05
@nniclausse https://gist.github.com/okeuday/b83b5d16775c0d13232fec34223f8f13 is the config.  I also noticed the output from `tsung_stats.pl` now has graphs that have no legend, at least in the output I had when interrupting the loadtest.  The crash seemed to always occur at the end of the loadtest.

**Comment by nniclausse** [comment] 2017-08-08 12:52
I can't reproduce the crash; which version of erlang did you use ?

**Comment by okeuday** [comment] 2017-08-08 17:13
@nniclausse 19.3

**Comment by nniclausse** [comment] 2017-08-09 15:06
I tried to run a test with OTP 19.3, no problem with current tsung git version. I noticed that you are using os monitoring with the host "business1". Does this host use the same erlang version as the other client nodes ?
Can you show me the  tsung_controller@xxxx.log file ?

**Comment by okeuday** [comment] 2017-08-09 16:24
@nniclausse The os monitoring with the host "business1" is a little different only because I am using a path to Erlang on that machine that is different than the loadtest clients, and the slave Erlang/OTP module attempts to enforce file operations on the master while not handling all file operations, which is an interesting bug I filed at https://bugs.erlang.org/browse/ERL-446 .  That issue only affected the startup of the loadtest clients due to how os_mon is started (and the module loading required, as described there).  I remember looking at the tsung_controller file and not seeing any issue, but I can try a new run to get the resulting files.

**Comment by okeuday** [comment] 2017-08-09 22:06
I have attached the tsung output when I attempt the loadtest using Alpine Linux on x86 with a LiveCD created based on the directions at https://github.com/CloudI/loadtests/tree/master/live_cd/alpine#readme .  The behavior is especially annoying because the `tsung.log` file is truncated during the crash somehow.
[crash1.tar.zip](https://github.com/processone/tsung/files/1213013/crash1.tar.zip)

**Comment by nniclausse** [comment] 2017-08-10 11:20
There is a weird error about io format, which caused ts_mon to be restarted, and the tsung.log file is emptied at this moment; I pushed a fix to not overwrite the log file in this case. For the reason of the crash, i don't know; it seems that the controller node is overloaded (there is a not of unusual errors in both tsungXXX@loadxx.log files; i also noticed the erlang beams are 32bits; on what kind of  hardware are your running the tests?

**Comment by okeuday** [comment] 2017-08-10 17:53
@nniclausse The loadtest client machines are 2 old 32bit pentium 4 machines I happen to have and they have worked in the past with tsung on a LiveCD, but I have switched from Ubuntu to Alpine for the LiveCD to keep the RAM use more minimal.

**Comment by tisba** [comment] 2018-08-22 11:49
I think the issue is superseded by https://github.com/processone/tsung/issues/318 - at least regarding a new Tsung release.

Could you open a new issue if your other problem (around crashes) still persists, @okeuday? Thank you!

**Closed by tisba** 2018-08-22 11:49 UTC
